### ISSUE TITLE
TypeError: __init__() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by teigao** [sth2018/FastWordQuery#1]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 475, in show_options
    opt_dialog = OptionsDialog(mw)
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 178, in __init__
    self.build()
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 236, in build
    self.build_mappings_layout(self.current_model)
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 302, in build_mappings_layout
    self.add_dict_layout(j, fld_name=name, **each)
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 430, in add_dict_layout
    self.fill_field_combo_options(field_combo, dict_name, dict_unique)
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 374, in fill_field_combo_options
    current_service = service_manager.get_service(service_unique)
  File "C:\Users\teigeg\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 61, in get_service
    return cls(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by sth2018** [comment]
请问你是否修改过service下面的文件？

**Comment by sth2018** [comment]
It's fixed.Thank you for your test!

**Comment by teigao** [comment]
谢谢，我再来试试
