### ISSUE TITLE
Mac Mojave10.14.2出现的bug，anki版本为2.52

### ISSUE THREAD

**Issue by insight123** [sth2018/FastWordQuery#110]
Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/insight/Library/Application Support/Anki2/addons/FastWQ.py", line 27, in <module>
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by sth2018** [comment]
麻烦更新至2.1版本，以后不再维护2.0版本的插件了。
