### ISSUE TITLE
Fast wq 1月27日更新完出现BUG，anki版本是2.0版本，更新前没问题，系统是win10 64位版本

### ISSUE THREAD

**Issue by luzhengyu827** [sth2018/FastWordQuery#115]
以下是弹出的bug信息。
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\main.py", line 165, in onOpenProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\johnn\AppData\Roaming\Anki2\addons\FastWQ.py", line 40, in start_here
    import fastwq
  File "C:\Users\johnn\AppData\Roaming\Anki2\addons\fastwq\__init__.py", line 26, in <module>
    from .gui import show_options, show_about_dialog, check_updates
ImportError: cannot import name check_updates

**Comment by sth2018** [comment]
再更新一下
