### ISSUE TITLE
之前用WQ的时候就遇到的问题

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#14]
这个问题，之前用WQ就遇到过，FWQ还是有，百思不得其解。

一本mdx词典，用Mdict查简体中文、繁体中文都可以查到同一个词条。

用wordquery和FWQ查简体“利赖”，没问题。（anki对应的field加入了这个词在词典中的解释）
用wordqueary无论查简体“逾远”还是繁体“逾遠”都查不到。（anki对应的field地方无变化）。但是用Mdict能查到“逾远”。

平常查中文词，也偶有这样的现象，在Mdict里能查到的，wq就是没反应。

下面是这两条txt格式的词条，看不出有什么区别。

> 利赖
> @@@LINK=利賴
> </>
> 利賴
> `1``2`利賴<small>〔利赖〕</small>`3``8`謂依傍；依靠。`9``6``4`淸`5``4`王夫之`5`《讀四書大全說·孟子·離婁上》：“言汝之所以舍正路，放本心，而放恣橫議者，只在此處：趁門風、圖利賴而已。”`7``6``4`淸`5``4`陳康祺`5`《郞潛紀聞》卷一：“文忠在西域剏興水利，開田至數十萬餘畝，至今利賴。”`7`
> </>
> 逾远
> @@@LINK=逾遠
> </>
> 逾遠
> `1``2`逾遠<small>〔逾远〕</small>`3``8`亦作“<a href="entry://踰遠">踰遠</a>”。`9``8``10`1`11`遠行。`9``6`《文選·顏延之＜赭白馬賦＞》：“有肆險以稟朔，或踰遠而納賮。”`4`李善`5`注引《孟子》：“有遠行者必以賮。”`7``8``10`2`11`猶遙遠。`9``6``4`晉`5``4`潘嶽`5`《寡婦賦》：“遙逝兮逾遠，緬邈兮長乖。”`7``6``4`唐`5``4`玄奘`5`《大唐西域記·摩揭陀國下》：“昔有苾芻，勤勵心身，屛居修定，歲月逾遠，不證聖果。”`7``6``4`廖平`5`《＜群經大義＞序》：“方今去古逾遠，史冊政典，日新月積，數十百倍於經傳。”`7`
> </>

**Comment by sth2018** [comment]
是txt字典吗？

**Comment by Steven630** [comment]
不是，是mdx格式的，只是把这两个词条的txt贴上来了。

如果有需要，可以提供词典源文件供测试。

**Comment by sth2018** [comment]
你提供一下对应的mdx文件给我测试看看

**Comment by Steven630** [comment]
链接: https://pan.baidu.com/s/1MJCZwIibC--pyn8DBlEWkA 密码: xdtf
就是这个汉语大词典。

逾远 Mdict繁体、简体都能查到，但是FWQ繁体简体都查不到。

麻烦啦！

**Comment by sth2018** [comment]
我用你给的文件测试过都可以查询得到

**Comment by sth2018** [comment]
查询的时候会提示选择css样式文件，选择你对应给的样式文件就好了

**Comment by Steven630** [comment]
我把原词典文件夹下面的db文件删除了，想重新试一下，结果选择option的时候提示错误：

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 490, in show_options
    opt_dialog = OptionsDialog(mw)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 178, in __init__
    self.build()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 236, in build
    self.build_mappings_layout(self.current_model)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 302, in build_mappings_layout
    self.add_dict_layout(j, fld_name=name, **each)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 436, in add_dict_layout
    self.fill_dict_combo_options(dict_combo, dict_name)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 348, in fill_dict_combo_options
    service = service_pool.get(cls.__unique__)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 72, in get_service
    return each()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 37, in _service
    return service(*args)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 437, in __init__
    mdx_builders[dict_path] = MdxBuilder(dict_path)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 102, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 130, in _make_mdx_index
    returned_index = mdx.get_index(check_block = self._check)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 823, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: unexpected end of data

**Comment by sth2018** [comment]
重启anki应该会重新生成.db文件的

**Comment by Steven630** [comment]
重启之后还是错误：

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 490, in show_options
    opt_dialog = OptionsDialog(mw)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 178, in __init__
    self.build()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 236, in build
    self.build_mappings_layout(self.current_model)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 302, in build_mappings_layout
    self.add_dict_layout(j, fld_name=name, **each)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 436, in add_dict_layout
    self.fill_dict_combo_options(dict_combo, dict_name)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 348, in fill_dict_combo_options
    service = service_pool.get(cls.__unique__)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 72, in get_service
    return each()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 37, in _service
    return service(*args)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 437, in __init__
    mdx_builders[dict_path] = MdxBuilder(dict_path)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 102, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 130, in _make_mdx_index
    returned_index = mdx.get_index(check_block = self._check)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 823, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: unexpected end of data

大概是因为我已经添加了那本词典，现在突然删了db，它找不到了。该怎么办呢，现在根本无法设置。一设置就是这个错误。

**Comment by Steven630** [comment]
后来用WQ重新build一次，然后FWQ也恢复正常了。

但是WQ生成.db文件的时候也没让选CSS，依旧查不到。

**Comment by sth2018** [comment]
你删除.db之后重启anki，打开options窗口，应该会卡住一段时间，因为生成.db文件比较耗时。另外我刚提交了一个新特性，会自动在mdx目录找缺失的css文件自动拷贝，如果不存在才会弹窗选择。

**Comment by Steven630** [comment]
又试了一次：

删除.db
重启anki
Tools——FastWQ
提示之前一样的错误

就是还没到options那里就提示错误了。

还试过把fastWQ卸载，删除文件夹后重装，也依然提示错误。

**Comment by sth2018** [comment]
你的字典目录里除了你传我的这个字典之后，还有其他字典吗？

**Comment by Steven630** [comment]
没有其他词典了。文件夹里的文件和分享的一样。

这一次我先从dict folders里把那本词典移除，然后删除.db，最后再添加到dict folders。

添加到dict folders的时候，提示错误：

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 258, in show_fm_dialog
    self.fill_dict_combo_options(cb, current_text)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 348, in fill_dict_combo_options
    service = service_pool.get(cls.__unique__)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 72, in get_service
    return each()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 37, in _service
    return service(*args)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 437, in __init__
    mdx_builders[dict_path] = MdxBuilder(dict_path)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 58, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META

**Comment by sth2018** [comment]
如果方便的话，你可以加我QQ（535373224），让我看看现场

**Comment by Steven630** [comment]
词典文件夹内的.db文件已删除
Options—dict folders内的文件夹路径已删除
重启anki，选择tools——FastWQ——dict folders——添加词典文件夹路径——按OK

过了一会，提示错误（见最后）。

会不会因为一开始的db文件是WQ而非FWQ创建的？我这本词典以前是用WQ查询的，这两天才改用的FWQ。你可以试试删除某个原来WQ创建词典的db文件，然后试着用FWQ重新创建。

还有就是同时使用WQ和FWQ有冲突吗？

现在唯一的解决方法是用WQ查询一次，等WQ创建db文件了，FWQ也能用了。

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 258, in show_fm_dialog
    self.fill_dict_combo_options(cb, current_text)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 348, in fill_dict_combo_options
    service = service_pool.get(cls.__unique__)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 72, in get_service
    return each()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 37, in _service
    return service(*args)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 437, in __init__
    mdx_builders[dict_path] = MdxBuilder(dict_path)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 102, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 130, in _make_mdx_index
    returned_index = mdx.get_index(check_block = self._check)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 823, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: unexpected end of data

**Comment by Steven630** [comment]
QQ删了很久了，现在马上去下一个。谢谢啦。先看看楼上的是不是能找到问题所在。

**Comment by sth2018** [comment]
根据你的描述，各种情况我都试了一下，都没出现异常:(
另外，WQ跟FWQ同时安装的话，除了快捷键之外不会存在其他冲突的。

**Comment by Steven630** [comment]
刚才更新到最新版本。

删除.db文件，移除dict folders里面的文件夹，重启anki

**添加文件夹时提示错误：**

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 415, in run
    self._builder = self._func()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 153, in _service
    return service(*args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 58, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META
Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 415, in run
    self._builder = self._func()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 153, in _service
    return service(*args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 58, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META

**然后又有错误：**
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 415, in run
    self._builder = self._func()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 153, in _service
    return service(*args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 58, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META

**这次比较坑，因为想“故伎重演”用WQ建立db，结果也提示错误：**

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\wquery\query.py", line 324, in run
    result = self.query(service_field, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\wquery\query.py", line 337, in query
    return self.service.active(service_field, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 165, in active
    self.builder.check_build()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 87, in check_build
    self._make_mdx_index()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 116, in _make_mdx_index
    os.remove(self._mdx_db)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\\u6f22\u8a9e\u5927\u8a5e\u51782018\\\u6f22\u8a9e\u5927\u8a5e\u5178.mdx.db'

**Comment by Steven630** [comment]
而且出现了一个0kb的db文件

**Comment by Steven630** [comment]
又试了一次，还是用WQ建立了。

**Comment by sth2018** [comment]
根据错误信息跟之前的问题是一样的:(

**Comment by Steven630** [comment]
好吧，还是搁置这个问题把。

之前update选项选了always update，以后一检查更新，跳出来都是说更新成功。有没有再改为手动更新的方法呢？

**Comment by sth2018** [comment]
把collection.media目录下的.ankihub.json文件删除

**Comment by Steven630** [comment]
好的，谢谢

**Comment by sth2018** [comment]
这个出现异常的原因好像是因为跟Word Query冲突引起的，因为字典文件被他占用了，你试试删除Word Query插件，或者把字典文件夹从Word Query里移除试试。
Word Query插件在Anki一启动就会占用设置了的字典文件夹中的字典文件，FastWQ只在使用时才会去打开字典文件。

**Comment by Steven630** [comment]
把WQ卸载了，还改了词典文件夹的名称。依然显示UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: unexpected end of data 的错误。

我已经放弃了……等周末再试试

**Comment by sth2018** [comment]
:( 那你用WQ生成db吧

**Comment by sth2018** [comment]
你好，能麻烦你帮我测试一个新的版本吗？就修复这个问题的？
[release.zip](https://github.com/sth2018/FastWordQuery/files/2180799/release.zip)

**Comment by Steven630** [comment]
好的，我马上试试

**Comment by Steven630** [comment]
这次可以了！

虽然一楼说的“愈远”还是查询不到，但是建立db没有问题，无错误提示。

太好啦~

**Comment by Steven630** [comment]
这次可以了！

虽然一楼说的“逾远”还是查询不到，但是建立db没有问题，无错误提示。

太好啦~

**Comment by sth2018** [comment]
我这里查询一直都没有问题:(，你的Anki版本是不是从低版本升上来的？试试卸载后重装看能不能解决
