### ISSUE TITLE
出现LDOCE6.mdx无法找到的错误

### ISSUE THREAD

**Issue by teigao** [sth2018/FastWordQuery#2]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 268, in btn_models_pressed
    self.build_mappings_layout(self.current_model)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 307, in build_mappings_layout
    self.add_dict_layout(i, fld_name=name)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 428, in add_dict_layout
    self.fill_dict_combo_options(dict_combo, dict_name)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\ui.py", line 347, in fill_dict_combo_options
    service = service_pool.get(cls.__unique__)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 72, in get_service
    return each()
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 37, in _service
    return service(*args)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\service\LDOCE6.py", line 14, in __init__
    super(Ldoce6, self).__init__(path)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 261, in __init__
    self.builder.get_header()
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 77, in get_header
    _()
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 54, in _
    mdx = MDX(self._mdx_file, only_header=True)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 645, in __init__
    MDict.__init__(self, fname, encoding, passcode, only_header)
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 102, in __init__
    self.header = self._read_header()
  File "C:\Users\teige\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\readmdict.py", line 271, in _read_header
    f = open(self._fname, 'rb')
IOError: [Errno 2] No such file or directory: u'D:\\mdx_server\\mdx\\LDOCE6.mdx'

**Comment by sth2018** [comment]
It's fixed. Thank you.
