### ISSUE TITLE
导入字典文件夹不成功

### ISSUE THREAD

**Issue by cododf** [sth2018/FastWordQuery#21]
导入字典文件夹时出错，一直显示“初始化词典..."窗口。
电脑系统WinXP.
Anki版本 2.0.51 Qt 4.8.4 PyQt 4.10

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\gui\options.py", line 70, in _before_build
    service = service_pool.get(cls.__unique__)
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\service\pool.py", line 39, in get
    return self.manager.get_service(unique)
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\service\manager.py", line 65, in get_service
    service = each()
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\service\base.py", line 179, in _service
    return service(*args, **kwargs)
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\service\base.py", line 684, in __init__
    if self.builder:
  File "C:\Documents and Settings\Administrator\Application Data\Anki2\addons\fastwq\libs\pystardict.py", line 534, in __len__
    return self.ifo.wordcount
AttributeError: 'NoneType' object has no attribute 'wordcount'

**Comment by sth2018** [comment]
可能有字典文件存在问题，因为我目前不在家，等我回去之后看。
另外能不能麻烦你共享一下出问题的字典给我？
