### ISSUE TITLE
Error with latest anki version

### ISSUE THREAD

**Issue by bgcldx** [sth2018/FastWordQuery#212]
**Describe the bug**

**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-05 10:20:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\8\AppData\Roaming\Anki2\addons21\1807206748\common.py", line 178, in <lambda>
    lambda mid=mid, i=i: set_options_def(mid, i))
  File "C:\Users\8\AppData\Roaming\Anki2\addons21\1807206748\common.py", line 53, in set_options_def
    config.update(data)
  File "C:\Users\8\AppData\Roaming\Anki2\addons21\1807206748\context.py", line 61, in update
    json.dump(
  File "json\__init__.py", line 179, in dump
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 353, in _iterencode_dict
TypeError: '<' not supported between instances of 'int' and 'str'**

**To Reproduce**
1. Go to 'Query'
2. Click on 'Selecting Config1/2/3...'

**Expected behavior**

**Comment by tosimplicity** [comment]
https://github.com/sth2018/FastWordQuery/issues/217#issuecomment-803544944
