### ISSUE TITLE
查询难词时，插件运行会出错

### ISSUE THREAD

**Issue by YuanZizai** [sth2018/FastWordQuery#22]
批量查询生词时，遇到难词时（比如：applique ）会出错，弹出Anki窗口显示以下错误信息。关闭弹窗后，一直显示“Querying...”Processing...，后续查询无法继续。

电脑系统Win10.
Anki版本 2.0.52
Qt 4.8.4 PyQt 4.10

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\__init__.py", line 47, in callback
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\__init__.py", line 55, in query_from_browser
    query_from_editor_all_fields(browser.editor)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\__init__.py", line 87, in query_from_editor_all_fields
    query_all([editor.note])
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\__init__.py", line 108, in query_all
    work_manager.start()
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 111, in start
    worker.run()
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 62, in run
    results, success_num, missed_css = query_all_flds(note)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 216, in query_all_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 245, in active
    return self.actions[fld_ord]()
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 92, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\fastwq\service\bing3tp.py", line 38, in fld_phonetic_us
    return seg.get('AmE', u'')
AttributeError: 'NoneType' object has no attribute 'get'

P.S. 很强大易用的插件，感谢作者的付出！

**Comment by sth2018** [comment]
收到，很快会修复，谢谢！

**Comment by YuanZizai** [comment]
很感谢作者的回复和关注，期待来自您的好消息！
