### ISSUE TITLE
制卡时出错，可能是由于配置文件紊乱，第一次制卡时未出错，但不知在哪里删除插件的配置文件

### ISSUE THREAD

**Issue by jiahe224** [sth2018/FastWordQuery#233]
**Describe the bug**

**To Reproduce**
1.点击卡片
2.使用FASTWQ
3.报错，但重启后内容会有更新，但更新的内容部分格式不对
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-09 15:47:06

Caught exception:
Traceback (most recent call last):
  File "C:\Users\huw\AppData\Roaming\Anki2\addons21\1807206748\common.py", line 80, in <lambda>
    action.triggered.connect(lambda: query_from_browser(browser))
  File "C:\Users\huw\AppData\Roaming\Anki2\addons21\1807206748\query\__init__.py", line 55, in query_from_browser
    query_from_editor_fields(browser.editor)
  File "C:\Users\huw\AppData\Roaming\Anki2\addons21\1807206748\query\__init__.py", line 90, in query_from_editor_fields
    query_all([editor.note], flush, fields)
  File "C:\Users\huw\AppData\Roaming\Anki2\addons21\1807206748\query\__init__.py", line 117, in query_all
    promot_choose_css(work_manager.missed_css)
  File "C:\Users\huw\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 127, in promot_choose_css
    Template.miss_css.format(dict=css['title'], css=css['file']))
AttributeError: type object 'Template' has no attribute 'miss_css'

**Comment by unix2dos** [comment]
解决了吗

**Comment by jiahe224** [comment]
> 解决了吗

忘了，好像是解决了，估计是把用户文件夹下三个文件夹里相关的都删掉，然后重新装插件，这里有点记录不知用不用的上，
文档：Anki.note
链接：http://note.youdao.com/noteshare?id=1b80deba055f42fd31f2f71378c29f88&sub=E19D06636E9641399CA533207CD160B9

天哪，我得帕金森了，才过去半年一点印象都没了
