### ISSUE TITLE
多个词典选项无法使用

### ISSUE THREAD

**Issue by sephirxth** [sth2018/FastWordQuery#24]
**Describe the bug**
1. 字典选项“朗文”使用时报错
2. 海词获取不到内容
3. 剑桥英英获取不到内容
4. 西语助手获取不到内容
**To Reproduce**
1. FASTWQ->option 选择字典
2. 

![image](https://user-images.githubusercontent.com/26618944/43302817-5da592a4-919f-11e8-91f9-6ab3a6d1ac99.png)

3. 点击Query
4. 一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\__init__.py", line 47, in callback
    return func(*args, **kwargs)
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\query\__init__.py", line 87, in query_from_editor_all_fields
    query_all([editor.note])
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\query\__init__.py", line 108, in query_all
    work_manager.start()
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 112, in start
    worker.run()
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 62, in run
    results, success_num, missed_css = query_all_flds(note)
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 216, in query_all_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 244, in active
    return self.actions[fld_ord]()
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 90, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\service\dict\longman.py", line 143, in fld_hyphenation
    return self._get_singledict('hyphenation')
  File "C:\Users\YouYuan\AppData\Roaming\Anki2\addons\fastwq\service\dict\longman.py", line 36, in _get_singledict
    rsp = rq.get("https://www.ldoceonline.com/dictionary/{}".format(self.word), headers={
NameError: global name 'rq' is not defined

**Expected behavior**
能够获取到相应内容
**Screenshots**

![image](https://user-images.githubusercontent.com/26618944/43302855-99bd2b3a-919f-11e8-9977-5995bc674f95.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/26618944/43302875-b7293380-919f-11e8-86a2-e0307c85176f.png)

![image](https://user-images.githubusercontent.com/26618944/43302866-a86925b2-919f-11e8-9a37-99ac3f6caa43.png)

**Additional context**
感谢开发者

**Comment by sth2018** [comment]
朗文词典的问题已修复，其他词典麻烦你直接用浏览器访问一下，看是否能查询到对应的内容。如果网页有而插件无法取得则插件存在BUG，如果网页也没有对应的内容，则是本身字典的问题。
谢谢！

**Comment by sephirxth** [comment]
朗文问题已解决。
如提问中的图，查询单词是bad，在剑桥中可以查到相关内容，海词词典中也可以查到，但插件获取不到。
![image](https://user-images.githubusercontent.com/26618944/43351502-8af8a808-9245-11e8-8d5e-c492731cc304.png)
![image](https://user-images.githubusercontent.com/26618944/43351521-c979b180-9245-11e8-927e-db43f270cb94.png)
![image](https://user-images.githubusercontent.com/26618944/43351523-d4f251d4-9245-11e8-8eaf-97ea5b890fc2.png)

**Comment by sephirxth** [comment]
朗文的问题已解决。
剑桥的可以获取到内容了。
海词词典仍没有内容
![image](https://user-images.githubusercontent.com/26618944/43351552-74a1be7c-9246-11e8-8992-a8d33ce1e41e.png)
![image](https://user-images.githubusercontent.com/26618944/43351586-ced382f4-9246-11e8-82be-2e4ea59fea83.png)
![image](https://user-images.githubusercontent.com/26618944/43351593-db45e5e0-9246-11e8-804a-3a43e4984da3.png)

**Comment by sth2018** [comment]
你能把海词的地址发一下给我吗？

**Comment by sephirxth** [comment]
http://dict.cn

**Comment by sth2018** [comment]
已修复，谢谢提交问题。
