### ISSUE TITLE
anki 2.1.50 版本下本地词典无法识别，且界面的“确定”按钮点击无反应

### ISSUE THREAD

**Issue by TtlyLynzie** [sth2018/FastWordQuery#241]
在 ⁨2.1.50 版本下导入的文件词典文件夹里的词典不能识别出来，且点击界面里的”确定“按钮没有反应

**Comment by TtlyLynzie** [comment]
Debug info:
Anki 2.1.50 (26d40c3a) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-04-18 20:09:48
Add-ons possibly involved: ⁨Fast Word Query Multi-threaded queries for words from local or web dictionaries⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/ttlynzie/Library/Application Support/Anki2/addons21/1807206748/gui/foldermanager.py", line 73, in add_folder
    config.update({'last_folder': dir_})
  File "/Users/ttlynzie/Library/Application Support/Anki2/addons21/1807206748/context.py", line 60, in update
    with open(self.path, 'w', encoding='utf-8') as f:
OSError: [Errno 30] Read-only file system: '_fastwqcfg.json'

**Comment by ffffffff01** [comment]
一样的问题，win10+anki 2.1.50，本地词典无法识别 [界面的“确定”按钮点击无反应

**Comment by aaabbb0088** [comment]
分享解決的方法，嘗試看看。

1. 找到插件資料夾下的 context.py 檔案

> 1807206748/context.py

2. 在 “config = Config(mw)” 這行前面，加上

```
wp = mw.pm.profileFolder()
mediaPath = os.path.join(wp, "collection.media") 
os.chdir(mediaPath)
```

說明一下發生什麼事。

2.1.49之前，開啟程式後，FastWQ預設的工作目錄會是在profile的collection.media。
所以可以正常讀取和寫入FastWQ的設定檔。

2.1.5X之後，FastWQ預設的工作目錄變成根目錄 / ，所以變成沒有權限寫入該資料夾。
上面的code是先抓到正確路徑，修改工作目錄，之後就正常了。

**Comment by ffffffff01** [comment]
> wp = mw.pm.profileFolder()
> mediaPath = os.path.join(wp, "collection.media") 
> os.chdir(mediaPath)

谢谢，按照您的方法，已经可以使用fastwq了。

不过发现另外一个问题，fastwq导入的单词解释，好像不会应用设置的css style，看上去比较混乱了，不知大佬可否帮忙看下？多谢！
