### ISSUE TITLE
词典请求

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#25]
首先欢迎大神回来 😄，披荆斩棘，将一个个问题解决，并增加新功能 👍 

有个小小的不情之请，能否抽空增加“吴音小字典”。

链接：http://wu-chinese.com/minidict/index.php

这个字典可以查单个字，也可以用吴语拼音查该发音的同音字。如：

http://wu-chinese.com/minidict/search.php?searchkey=%E6%98%93 （易）
http://wu-chinese.com/minidict/search.php?searchkey=yih （发音“yih”）

搜索结果都在table class="results"的表格里。但是关键字和拼音都是图片格式，最右边一列是真人发音。

其实也可以搜索多个字，但搜索结果其实只是把各个字的结果合并，如：
http://wu-chinese.com/minidict/search.php?searchkey=%E6%8B%85%E5%BD%93 （担当）

不知道能否实现查询结果就是那个results的表格，而且anki上点最右侧的喇叭可以听到发音？

麻烦了，非常感谢。

**Comment by sth2018** [comment]
这个词典会不会太小众了点？

**Comment by Steven630** [comment]
确实有点小众 😭。  如果觉得不适合占用词典的公共栏，能否私下分享个增加该词典的版本文件？拜托啦

**Comment by sth2018** [comment]
可以

**Comment by Steven630** [comment]
谢谢！

**Comment by Steven630** [comment]
到时候可以一起发一个FWQ界面的英文翻译，我可以润色，聊表谢意。

**Comment by sth2018** [comment]
OK，谢谢！

**Comment by Steven630** [comment]
那在线播放音频能实现吗？要不行声音就不要了

**Comment by sth2018** [comment]
我还没找到相关的文档，Anki的文档比较少，很多都只能靠摸索，头疼。
我先给你个无声版吧

**Comment by Steven630** [comment]
非常感谢，无声版也很好了！我有一两个mdx词典，经FWQ查询后可以在anki上点击后在线听发音，不知道是怎么实现的。

**Comment by sth2018** [comment]
那你把查询到的内容发我看看

**Comment by Steven630** [comment]
好的，稍等

**Comment by sth2018** [comment]
[wu_chinese.zip](https://github.com/sth2018/FastWordQuery/files/2238494/wu_chinese.zip)
带离线图片的吴音小词典

**Comment by Steven630** [comment]
拜谢。今天出门，明天回去试试。

**Comment by Steven630** [comment]
试了一下，非常完美。不知道声音以后还能否实现呢？（我太贪得无厌了……）

另外用本地汉语大词典的时候查询到一半出现错误：

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 62, in run
    results, success_num, missed_css = query_all_flds(note)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 216, in query_all_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 496, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 244, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 90, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 531, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 582, in get_default_html
    result = self.builder.mdx_lookup(self.word)  # self.word: unicode
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 306, in mdx_lookup
    lookup_result_list.append(self.get_mdx_by_index(mdx_file, index))
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 270, in get_mdx_by_index
    data = self.get_data_by_index(fmdx,index)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 265, in get_data_by_index
    _record_block = zlib.decompress(record_block_compressed[8:])
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

好像是查到某个字的时候的问题，按close后继续查询，到99%卡住了。

偶然发现查“龟”就会有这个问题。

最后还有个疑问，FWQ现在支持2.1版本了，看到有几个在线词典更新了。不知道这个吴音字典需要更新吗。

再次感谢高手出手相助。

**Comment by sth2018** [comment]
在2.0上使用不需要更新，2.1我也没试过，不过我使用了一下2.1感觉稳定性还有待加强。

**Comment by sth2018** [comment]
另外你如果要更新到最新版本的FastWQ插件的话，先删除原来的插件重新安装，在线更新会出错。

**Comment by sth2018** [comment]
出现问题是你之前有共享的那本汉语大词典吗？我在我机器上测试没有问题呢。

**Comment by Steven630** [comment]
好的，谢谢提醒。

出错的就是那本，挺奇怪的。再加上之前查不到的词，难道真是我系统的问题，唉…… 改天我重装试试吧。
