### ISSUE TITLE
macOS Ventura V13.0.1, could not work, and report OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by alexchenyu** [sth2018/FastWordQuery#257]
macOS Ventura V13.0.1
After successfully adding FastWordQuery, Go to Tools->FastWQ->Choose Note Type, and get error messages like below. 
and even after I chmod in the target folder, it still don't work.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.0.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-10 21:26:12
Add-ons possibly involved: ⁨Fast Word Query Multi-threaded queries for words from local or web dictionaries⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Anki2/addons21/1807206748/gui/options.py", line 212, in accept
    self.save()
  File "/Users/alex/Library/Application Support/Anki2/addons21/1807206748/gui/options.py", line 322, in save
    config.update(data)
  File "/Users/alex/Library/Application Support/Anki2/addons21/1807206748/context.py", line 60, in update
    with open(self.path, 'w', encoding='utf-8') as f:
OSError: [Errno 30] Read-only file system: '_fastwqcfg.json'

**Comment by AnkiStudio** [comment]
https://github.com/sth2018/FastWordQuery/issues/241#issuecomment-1172900801

You could fix the issue by above link.
