### ISSUE TITLE
win11电脑装的Anki Q6 ，用不了FW，各位大神能帮忙看看吗？

### ISSUE THREAD

**Issue by lishan256** [sth2018/FastWordQuery#264]
各位大神能帮忙看看什么原因吗？
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-02 19:46:10

[Errno 13] Permission denied: '_fastwqcfg.json'
Traceback (most recent call last):
  File "C:\Users\freec\AppData\Roaming\Anki2\addons21\1807206748\gui\setting.py", line 117, in accept
    self.save()
  File "C:\Users\freec\AppData\Roaming\Anki2\addons21\1807206748\gui\setting.py", line 146, in save
    config.update(data)
  File "C:\Users\freec\AppData\Roaming\Anki2\addons21\1807206748\context.py", line 60, in update
    with open(self.path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '_fastwqcfg.json'

**Describe the bug**
刚换的新电脑，装了anki之后，装了这个插件。按照需要设定option选项，结果就弹出来了这个错误提示。我应该怎么解决呢？

**Desktop (please complete the following information):**
 - OS: anki-2.1.61-windows-qt6

**Comment by SOREMUZ** [comment]
你好，已经有好心人修复这个插件了，请在这里安装，please get the fixed version of FWQ from here : https://ankiweb.net/shared/info/103636257
