### ISSUE TITLE
运行错误 

### ISSUE THREAD

**Issue by GoldenUniverse** [sth2018/FastWordQuery#273]
错误
运行出错。请在启动Anki时按住「Shift」键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-02-13 00:21:15

[Errno 13] Permission denied: '_fastwqcfg.json'
Traceback (most recent call last):
  File "C:\Users\Heavy_Sigh\AppData\Roaming\Anki2\addons21\1807206748\gui\foldermanager.py", line 89, in accept
    self.save()
  File "C:\Users\Heavy_Sigh\AppData\Roaming\Anki2\addons21\1807206748\gui\foldermanager.py", line 99, in save
    config.update(data)
  File "C:\Users\Heavy_Sigh\AppData\Roaming\Anki2\addons21\1807206748\context.py", line 60, in update
    with open(self.path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '_fastwqcfg.json'

**Comment by GoldenUniverse** [comment]
怎么解决？？
