### ISSUE TITLE
多词查询

### ISSUE THREAD

**Issue by colizuo** [sth2018/FastWordQuery#54]
**Describe the bug**
之前那个注释谢谢你的回答，现在又遇到了一个新的bug，在使用fastwordquery 做批量查询例句的时候出现了这样的情况：
Traceback (most recent call last):
  File "/home/collins/.local/share/Anki2/addons/fastwq/query/worker.py", line 62, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "/home/collins/.local/share/Anki2/addons/fastwq/query/common.py", line 241, in query_flds
    qr = service.active(task['f'], task['w'])
  File "/home/collins/.local/share/Anki2/addons/fastwq/service/base.py", line 285, in active
    return self.actions[fld_ord]()
  File "/home/collins/.local/share/Anki2/addons/fastwq/service/base.py", line 109, in _deco
    res = fld_func(self, *args, **kwargs)
  File "/home/collins/.local/share/Anki2/addons/fastwq/service/dict/bing3tp.py", line 76, in fld_samples
    for i, seg in enumerate(segs):
TypeError: 'NoneType' object is not iterable

**Desktop (please complete the following information):**
 - OS: linux
 - Version 2.0.52

**Comment by colizuo** [comment]
我试了一下好像是打开后面那个选词填空才会出现的问题。

**Comment by sth2018** [comment]
看看是否还有问题
