### ISSUE TITLE
安装成功,打开anki就报错

### ISSUE THREAD

**Issue by AzisHsu** [sth2018/FastWordQuery#62]
看到介绍，感觉太棒了，，这就是我要的插件。但不幸的是，我并不能使用。win10，anki2.0，虽然安装成功。但是，一打开anki就报错。情况如下：

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\main.py", line 165, in onOpenProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\����\AppData\Roaming\Anki2\addons\FastWQ.py", line 39, in start_here
    import fastwq
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\__init__.py", line 25, in <module>
    from .gui import show_options, show_about_dialog, check_updates
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\gui\__init__.py", line 3, in <module>
    from .common import *
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\gui\common.py", line 24, in <module>
    from .options import OptionsDialog
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\gui\options.py", line 33, in <module>
    from ..service import service_manager, service_pool
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\service\__init__.py", line 24, in <module>
    service_manager = ServiceManager()                             # Service Manager
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 40, in __init__
    self.update_services()
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 48, in update_services
    self.web_services, self.local_custom_services = self._get_services_from_files()
  File "C:\Users\����\AppData\Roaming\Anki2\addons\fastwq\service\manager.py", line 68, in _get_services_from_files
    mypath = os.path.join(os.path.dirname(os.path.realpath(__file__)), service_path)
  File "ntpath.py", line 85, in join
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 7: invalid continuation byte

**Comment by sth2018** [comment]
这可能是中文目录引起的，我需要调试一下才能确定问题。

**Comment by sth2018** [comment]
已经修复了，你删除插件然后重装就好了

**Comment by AzisHsu** [comment]
謝謝你，果然可以了。確實比Wq方便。
