### ISSUE TITLE
批量查询有道音标时提示错误

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#7]
批量查询有道词典音标，才查询了几个，就出现下列错误。按close之后，便不继续查询。窗口一直卡在“Querying”的界面。

建议可以自动忽视错误，不因某个查询错误而影响后面的查询。

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query.py", line 93, in run
    if self.manager.update(note, results, success_num):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query.py", line 145, in update
    self.fields += val
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by sth2018** [comment]
已找到原因并修复了，谢谢！
当你的单词在有道查询失败的时候会出现这个异常（网络原因或友道无此单词等）
多谢提交异常！
