### ISSUE TITLE
快查询完跳出错误

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#92]
查询一批词语，快查询完提示错误：

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 62, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 241, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 538, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 285, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 109, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 574, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 626, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 639, in _get_default_html
    return self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 631, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 601, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\service\base.py", line 581, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 303, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db,keyword,ignorecase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons\fastwq\libs\mdict\mdict_query.py", line 288, in lookup_indexes
    cursor = conn.execute(sql)
sqlite3.OperationalError: near "stylesheet": syntax error

**Comment by sth2018** [comment]
用的是什么词典？查的什么词出的错知道吗？

**Comment by Steven630** [comment]
用的本地的汉语词典，具体哪个词不太清楚呢，好像是98-99%时候发生的。

**Comment by Steven630** [comment]
今天查汉语词典，又出现下面这个错误。已经升级了2.1

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.8 (71e0c880) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\worker.py", line 63, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 242, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 544, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 288, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 116, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 580, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 633, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 638, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 608, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 588, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 306, in mdx_lookup
    lookup_result_list.append(self.get_mdx_by_index(mdx_file, index))
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 273, in get_mdx_by_index
    record = self._replace_stylesheet(record)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 113, in _replace_stylesheet
    txt_list = re.split('`\d+`', txt)
  File "C:\Program Files\Python36\lib\re.py", line 212, in split
<class 'TypeError'>: cannot use a string pattern on a bytes-like object

**Comment by Steven630** [comment]
2.1也有同样错误，“汉语大词典”，最后提示：

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.8 (71e0c880) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\worker.py", line 63, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 242, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 544, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 288, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 116, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 580, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 633, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 646, in _get_default_html
    return self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 638, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 608, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 588, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 311, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db,keyword,ignorecase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 296, in lookup_indexes
    cursor = conn.execute(sql)
<class 'sqlite3.OperationalError'>: near "stylesheet": syntax error
Caught exception:
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\worker.py", line 63, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 242, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 544, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 288, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 116, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 580, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 633, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 646, in _get_default_html
    return self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 638, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 608, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 588, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 311, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db,keyword,ignorecase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 296, in lookup_indexes
    cursor = conn.execute(sql)
<class 'sqlite3.OperationalError'>: near "stylesheet": syntax error
Caught exception:
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\worker.py", line 63, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 242, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 544, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 288, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 116, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 580, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 633, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 646, in _get_default_html
    return self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 638, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 608, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 588, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 311, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db,keyword,ignorecase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 296, in lookup_indexes
    cursor = conn.execute(sql)
<class 'sqlite3.OperationalError'>: near "stylesheet": syntax error
Caught exception:
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\worker.py", line 63, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\query\common.py", line 242, in query_flds
    qr = service.active(task['f'], task['w'])
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 544, in active
    return super(LocalService, self).active(fld_ord, word)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 288, in active
    return self.actions[fld_ord]()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 116, in _deco
    res = fld_func(self, *args, **kwargs)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 580, in fld_whole
    html = self.get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 633, in get_default_html
    self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 646, in _get_default_html
    return self._get_default_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 638, in _get_default_html
    result = self.get_html()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 608, in get_html
    html = self._get_definition_mdx()
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\service\base.py", line 588, in _get_definition_mdx
    content = self.builder.mdx_lookup(self.word, ignorecase=config.ignore_mdx_wordcase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 311, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db,keyword,ignorecase)
  File "C:\Users\malanting\AppData\Roaming\Anki2\addons21\1807206748\libs\mdict\mdict_query.py", line 296, in lookup_indexes
    cursor = conn.execute(sql)
<class 'sqlite3.OperationalError'>: near "stylesheet": syntax error

**Comment by sth2018** [comment]
查的是什么词？是今天更新的最新版本吗？

**Comment by Steven630** [comment]
是今天的版本。

查了好多词（在browse里多选几十个词查询），还是在快查完的时候提示的，而且最后结果似乎没有异常。所以猜测可能和词无关，只要批量查询就会有问题。

**Comment by sth2018** [comment]
那麻烦你把课件导出共享一下给我

**Comment by Steven630** [comment]
不知道怎么选部分词导出，所以就导出了整个deck

链接: https://pan.baidu.com/s/1OWIuWMbhWbtl6S7wKkCw9w 提取码: 7p9c
