### ISSUE TITLE
使用Cloze Word查询的时候出现error

### ISSUE THREAD

**Issue by Sapph1reX** [sth2018/FastWordQuery#93]
如题，查询过程中报错

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\query\worker.py", line 62, in run
    results, success_num, missed_css = query_flds(note, self.manager.query_fields)
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 244, in query_flds
    qr['result'] = cloze_deletion(qr['result'], word)
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\query\common.py", line 285, in cloze_deletion
    if _stemmer.stemWord(word).lower() == term:
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\libs\snowballstemmer\basestemmer.py", line 342, in stemWord
    result = self._stem_word(word)
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\libs\snowballstemmer\basestemmer.py", line 326, in _stem_word
    self._stem()
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\libs\snowballstemmer\english_stemmer.py", line 999, in _stem
    if not self.r_prelude():
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\libs\snowballstemmer\english_stemmer.py", line 229, in r_prelude
    if not self.in_grouping(EnglishStemmer.g_v, 97, 121):
  File "C:\Users\surface\AppData\Roaming\Anki2\addons\fastwq\libs\snowballstemmer\basestemmer.py", line 36, in in_grouping
    ch = ord(self.current[self.cursor])
IndexError: string index out of range

**Comment by sth2018** [comment]
有没有设置单词填空？设置的内容是什么？

**Comment by Sapph1reX** [comment]
![untitled picture](https://user-images.githubusercontent.com/38830276/48675400-66125f00-eb93-11e8-933b-71073f58c15c.png)

**Comment by Sapph1reX** [comment]
差不多弄好了，但词中有连字符或者空格时可能会没有生成Cloze，请问这种情况怎么办呢（我记得有个地方可以设置Cloze的格式？）

**Comment by sth2018** [comment]
设置里面添加了一项可以自主设置，但是如果设置的格式错的话会引起异常
有空格或有连字符会无法生成，因为同词查询算法并不完美

**Comment by Sapph1reX** [comment]
用Cloze Word加多线程查询的时候还是经常有Error（没有更改Cloze的格式），查到一半报错之后就停下来不动了，不知道是怎么回事？
